"""Add email verification and user approval fields

Revision ID: d5b76bdfeff2
Revises: 
Create Date: 2026-01-14 23:16:26.454361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b76bdfeff2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then update existing records, then make NOT NULL
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing records to have default values
    op.execute("UPDATE users SET is_email_verified = False WHERE is_email_verified IS NULL")
    
    # Now make the column NOT NULL (SQLite specific workaround)
    op.execute("CREATE TABLE users_temp AS SELECT * FROM users")
    op.drop_table('users')
    op.execute("""
        CREATE TABLE users (
            id INTEGER PRIMARY KEY,
            email VARCHAR NOT NULL,
            username VARCHAR NOT NULL,
            hashed_password VARCHAR NOT NULL,
            full_name VARCHAR,
            role VARCHAR NOT NULL,
            is_active BOOLEAN NOT NULL,
            is_email_verified BOOLEAN NOT NULL,
            email_verification_token VARCHAR,
            email_verification_expires DATETIME,
            created_at DATETIME,
            updated_at DATETIME,
            last_login DATETIME,
            department_id INTEGER,
            FOREIGN KEY(department_id) REFERENCES departments (id)
        )
    """)
    op.execute("INSERT INTO users SELECT * FROM users_temp")
    op.drop_table('users_temp')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
